#str(subSetData)
submet1 <- as.numeric(subbase$Sub_metering_1)
submet2 <- as.numeric(subbase$Sub_metering_2)
submet3 <- as.numeric(subbase$Sub_metering_3)

png("plot3.png", width=480, height=480)
plot(date, submet1, type="l", ylab="Energy Submetering", xlab="")
lines(date, submet2, type="l", col="red")
lines(date, submet3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()
